server:
  port: 7078
spring:
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    password: admin
    username: admin
    virtual-host: my_vhost
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
  redis:
    host: 192.168.0.100
    port: 6379
    password: 123456
